# -*- coding: utf-8 -*-
"""game_score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5XzgudVEchprmXH0DRaBVpUfYCJOphI
"""

# game_score.py
# This program collects a player's game details and calculates the average score per game.

# Step 1: Input Collection - Player Name
player_name = input("Enter player name: ")

# Step 2: Numeric Input Processing - Games Played
games_played = int(input("Enter number of games played: "))

# Step 3: Score Data Entry - Total Score
total_score = int(input("Enter total score: "))

# Step 4: Computation - Average Score
# Avoid division by zero
if games_played > 0:
    average_score = total_score / games_played
else:
    average_score = 0

# Step 5: Output Display (Required Format)
print("\nPlayer:", player_name)
print("\nGames Played:", games_played)
print("\nTotal Score:", total_score)
print("\nAverage Score:", average_score)